# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-13 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190413_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 6, 2, 0, 650556, tzinfo=utc)),
        ),
    ]
