# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-13 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190413_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 6, 49, 13, 918116, tzinfo=utc)),
        ),
    ]
