# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-13 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190413_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 7, 0, 24, 265449, tzinfo=utc)),
        ),
    ]
